### ISSUE TITLE
Issue with Vim Tmux Navigator?

### ISSUE THREAD

**Issue by thewatts** [tmate-io/tmate#33] opened 2014-04-08 18:40 UTC
There's an issue using `tmate` and [Vim Tmux Navigator](https://github.com/christoomey/vim-tmux-navigator) together.

It looks like the issue is because of mismatching versions of `tmate` and `tmux`.
[More info here](https://github.com/christoomey/vim-tmux-navigator#it-doesnt-work-in-tmate) and [here](https://github.com/christoomey/vim-tmux-navigator/issues/27).

**Comment by murphyrandle** [comment] 2015-01-08 03:12
Youch, I'm hoping for this also, but I don't think I'll be much help. @nviennot Thanks for tmate!

**Comment by nviennot** [comment] 2015-01-08 03:19
If you put this in your .bashrc / .zshrc:

```bash
if [[ $TMUX =~ tmate ]]; then alias tmux=tmate; fi 
```
does it help?

**Comment by murphyrandle** [comment] 2015-01-08 03:21
I'm afraid it wouldn't help me much, the thing that chafes me is that I can't use `pane_current_path` in tmate to have new splits be in the same directory as the originating split.

It doesn't seem like aliasing tmux to tmate would solve that at all, as it's a tmux api incompatibility. Right?

**Comment by nviennot** [comment] 2015-01-08 03:26
oh I see. So for the directory split issue, you can have a quick hack:

if you have in your `~/.tmux.conf`:

```
bind -n M-\ split-window -h -c '#{pane_current_path}'
bind -n M-- split-window -v -c '#{pane_current_path}'
```

put in your '~/.tmate.conf`:

```
bind -n M-\ split-window -h
bind -n M-- split-window -v
```

That is, you just remove the `-c ... ` argument.

**Comment by murphyrandle** [comment] 2015-01-08 03:34
Well, I feel silly. For now then, I don't feel an urgent need for 1.9 :) I've downgraded tmux to 1.8
Thanks for your help!

**Comment by nviennot** [comment] 2015-01-08 03:36
updating tmate to tmux 1.9 is really on my list, but I'm being a little conservative because I'm not sure what could break and all that. I don't want to introduce regressions, because I know I won't have the time to deal with them. Sorry about that :)

**Comment by murphyrandle** [comment] 2015-01-09 00:33
Not a problem. Thank you! 

—

**Comment by pmccarren** [comment] 2015-03-25 21:33
Any plans for adopting tmux 1.9a?

**Comment by nviennot** [comment] 2015-03-25 22:30
Yes! But no time yet

**Comment by jondkinney** [comment] 2015-04-16 04:18
+1 if only I knew C I'd love to help out :/

**Comment by daviddavis** [comment] 2015-04-16 18:48
:+1: is this the issue being used to track 1.9 support?

**Comment by christoomey** [comment] 2015-10-25 02:39
There is a new PR in work on the vim-tmux-navigator repo that automatically detects `tmate` based on [this snippet](https://github.com/nviennot/tmate/issues/33#issuecomment-69130656) from @nviennot.

You can see the PR here: https://github.com/christoomey/vim-tmux-navigator/pull/89

P.S. Thanks a ton for tmate @nviennot, it's great!

**Comment by nviennot** [comment] 2015-10-25 09:16
I'll update to the latest tmux soon :)

**Comment by christoomey** [comment] 2015-11-30 00:12
Follow up for anyone using Vim Tmux Navigator. I've gone ahead and merged the fix (christoomey/vim-tmux-navigator#89) so if you pull locally all should be set. This works with the current `tmate`. I'll leave to @nviennot to close, but I believe this issue is resolved.

**Comment by nviennot** [comment] 2016-01-03 03:41
tmate has been upgraded to latest version of tmux.

Run brew install --HEAD tmate if you use homebrew. Install from sources (git HEAD) if not.

**Closed by nviennot** 2016-01-03 03:41 UTC
